### ISSUE TITLE
docs: domain name in init.py

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-s3#12]
https://github.com/inveniosoftware/invenio-s3/blob/bb03233923edd52c34137b3995c03dcc5789d29e/invenio_s3/__init__.py#L21

This should not include the domain URL just hte bucket nme

**Comment by egabancho** [comment]
https://github.com/inveniosoftware/invenio-s3/commit/e2ef7e4fc3354d511da0e44271d233eeba701c82
