### ISSUE TITLE
make new release

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-s3#13]

**Comment by ppanero** [comment]
[Not urgent]
Hi @egabancho! just wondering if you have an estimation of when you will release it. To see if it can make it into RDM feb release. If so will it have breaking changes (i.e. v1.1.0) or not (i.e. 1.0.2) ?

Thanks!

**Comment by egabancho** [comment]
We can release now if you want, there are no breaking changes so it should be a minor version I guess.

I just made a PR for the big files multipart upload issue, #15, it would be nice if we could include this in the release, I just need to find a way to test it properly! Any ideas? ☺️

**Comment by Herrner** [comment]
I got a test case at hand... 😉

**Comment by ppanero** [comment]
@egabancho As soon as `1.0.2` is released I have already made the tests to include it in cookiecutter for RDM. So it would be in, with a `min.io` instance. https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/39 (It's just failing cuz 1.0.2 is not there hehe)

Testing the multipart upload could be done on the RDM release of feb, or on any other instance you are thinking about. :) Thanks!!

**Comment by ppanero** [comment]
closed by https://github.com/inveniosoftware/invenio-s3/pull/17
