### ISSUE TITLE
remove python 2 support

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-s3#16]

**Comment by Herrner** [comment]
I liked the old title...

**Comment by egabancho** [comment]
Me too, but the rocket wasn't rendered properly 😢

**Comment by ppanero** [comment]
I think this was fixed here: https://github.com/inveniosoftware/invenio-s3/pull/17 Unless you mean deeper code changes not just travis, setup.py and release :)

**Comment by egabancho** [comment]
i.e. https://github.com/inveniosoftware/invenio-s3/blob/master/setup.py#L51
