### ISSUE TITLE
invenio-s3 repeats the bucket name as path

### ISSUE THREAD

**Issue by Herrner** [inveniosoftware/invenio-s3#2]
the name of the bucket from the S3 configuration gets somehow repeated as part of path, so that files are written to `s3://bucket_name/bucket_name/files`

**Comment by egabancho** [comment]
I am no longer able to reproduce the issue. It seems that the files are now in the correct location.  
When using the URI `s3://default/f7/14/adaa-04f2-48e8-9a6b-de2f57948ce1/data` stored in `files_files.uri`, the following file structure is created:

```
$ tree data
data
└── default
    └── f7
        └── 14
            └── adaa-04f2-48e8-9a6b-de2f57948ce1
                └── data
```

@Herrner, please feel free to reopen the issue if you are still able to replicate it.
